image: stormenroute/storm-enroute-build:0.15

before_script:
  - |
    eval `ssh-agent -s`
    echo "exec cat" > ap-cat.sh
    chmod a+x ap-cat.sh
    export DISPLAY=1
    echo "$SSH_KEY_PASS" | SSH_ASKPASS=./ap-cat.sh ssh-add ~/.ssh/id_rsa
    rm ap-cat.sh
    export SSH_KEY_PASS=""
    export DISPLAY=""
  - |
    mkdir -p ~/.sbt/0.13/
    echo 'scalacOptions ++= Seq("-Xmax-classfile-name", "90")' > ~/.sbt/0.13/local.sbt
  - git clone git@ci.storm-enroute.com:storm-enroute/super-storm-enroute.git ~/.super-storm-enroute

after_script:
  - rm -rf ~/.super-storm-enroute


gate-ubuntu:
  tags:
    - ubuntu
    - gate
  script:
    - ~/.super-storm-enroute/tools/ci reactors $(pwd)
<<<<<<< Updated upstream
=======
  cache:
    paths:
      - /root/.ivy2/
      - /root/.sbt/
  artifacts:
    paths:
      - ~/.super-storm-enroute/reactors/target/videos/
    expire_in:
      1 week
>>>>>>> Stashed changes


gate-standalone-ubuntu:
  tags:
    - ubuntu
    - gate
  script:
    - ~/.super-storm-enroute/tools/sbt scalastyle
    - ~/.super-storm-enroute/tools/sbt test
    - ~/.super-storm-enroute/tools/sbt clean
    - ~/.super-storm-enroute/tools/sbt ++2.12.2 test
<<<<<<< Updated upstream
=======
  cache:
    paths:
      - /root/.ivy2/
      - /root/.sbt/
  artifacts:
    paths:
      - ~/.super-storm-enroute/reactors/target/videos/
    expire_in:
      1 week
>>>>>>> Stashed changes


bench-ubuntu:
  tags:
    - ubuntu
    - bench
  script:
    - ~/.super-storm-enroute/tools/ci --bench=True . $(pwd)
  cache:
    paths:
      - /root/.ivy2/
      - /root/.sbt/
